name: Dockerfile scanning 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  container-scanning: 
    runs-on: ubuntu-latest 
    name: dockerfile  scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: SCAN the Dockerfile 
      run : | 
              cd $GITHUB_WORKSPACE 
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              sudo chmod +x /bin/hadolint
              hadolint Dockerfile 
    - uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: /tmp/output # or path/to/artifact

