name: Docker build 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  docker-build: 
    runs-on: ubuntu-latest 
    name: Build 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: joshua/rails-app 
          tags: latest