name: container-scanning 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  container-scanning: 
    runs-on: ubuntu-latest 
    name: container scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Run Trivy vulnerability scanner
      run : |  
              cd $GITHUB_WORKSPACE 
              docker build -t test . 
              curl -sfL  https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh  | sh -s -- -b /usr/local/bin v0.21.3 
              trivy image ghcr.io/joshuawe45/rails-app:latest >> /tmp/trivy || true 
    - uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: /tmp/trivy 

    - name: docker-scan 
      run : | 
              docker scan ghcr.io/joshuawe45/rails-app:latest >> /tmp/scan || true 
    - uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: /tmp/scan 