name: dast 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  dast-scanning: 
    runs-on: ubuntu-latest 
    name: dast scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: SCAN the application 
      run : | 
              cd $GITHUB_WORKSPACE
              docker-compose build
              docker-compose run web rails db:setup
              docker-compose up -d 
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
       target: 'http://localhost:3000/'
 

        