name: Secret Scanning 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  dast-scanning: 
    runs-on: ubuntu-latest 
    name: Secret Scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
