name: Sbom 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  sbom : 
    runs-on: ubuntu-latest 
    name: Sbom 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Run syft 
      run : | 
              curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
              syft joshuawe45/certification:rail
