name: container-scanning 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  container-scanning: 
    runs-on: ubuntu-latest 
    name: container scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 'ghcr.io/joshuawe45/rails-app:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
          sarif_file: 'trivy-results.sarif'     
    - name: docker-scan 
      run : | 
              docker scan ghcr.io/joshuawe45/rails-app:latest >> /tmp/output
    - uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: /tmp/output