name: Sca 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  brakeman: 
    runs-on: ubuntu-latest 
    name: bundler scan 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Install the bundler audit  
      run : | 
           gem install bundler-audit
           bundle-audit