name: DAST 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  dast: 
    runs-on: ubuntu-latest 
    name: bundler scan 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: Run the application 
      run : | 
            docker-compose build
            docker-compose run web rails db:setup
            docker-compose up -d 