name: Dockerfile scanning 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  container-scanning: 
    runs-on: ubuntu-latest 
    name: dockerfile  scanning 
    steps: 
    - name: Checkout the code 
      uses: actions/checkout@v2
    - name: SCAN the Dockerfile 
      run : | 
              cd $GITHUB_WORKSPACE 
              docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile >> /tmp/output 
    - uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: /tmp/output # or path/to/artifact

